### ISSUE TITLE
Change menu items.

### ISSUE THREAD

**Issue by thomasve-DANS** [tvanerven/amy#2]
Items to be deleted/hidden:
- Airports

Rename:
- Membership -> Sponsors
- Organizations -> Hosts
- Events -> Schools
- Training -> Instructor training

**Comment by hughshanahan** [comment]
This is good - my previous comments on tags may need to be updated in this light.

**Comment by thomasve-DANS** [comment]
Hi @hughshanahan , @pherterich , this has been deployed to https://amy.charminghat.nl. Can you validate that this is what you had in mind?

**Comment by pherterich** [comment]
Looks ok to me but it's probably down to @hughshanahan to confirm. Just a small note that under the "More" menu, there's a "merge events" item which when clicking on it changes to merge schools, but maybe that can be adjusted in the menu already so no one gets confused and starts looking for events?

**Comment by thomasve-DANS** [comment]
I see I missed a spot; I'll amend that today. Good spot.
