### ISSUE TITLE
Update list of contributions

### ISSUE THREAD

**Issue by thomasve-DANS** [tvanerven/amy#6]
| Highlight here: either DELETE or RENAME TO xxx or KEEP
-- | --
Financial |  KEEP
Person-days |  KEEP
Other |  KEEP

</div></b>

**Comment by pherterich** [comment]
If they are all KEEP now, maybe this can just be closed as it doesn't require any work from @thomasve-DANS ?

**Comment by hughshanahan** [comment]
Agreed.
